# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-8-tools-deps
      - image: amazon/opendistro-for-elasticsearch:1.12.0
        environment:
          discovery.type: single-node

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "deps.edn" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - add_ssh_keys:
          fingerprints:
            - "9b:3c:90:2a:d7:c1:76:ed:23:c8:83:b6:8b:cc:e3:18"

      - run:
          name: Fetch deps
          command: |
            cp .circleci/settings.xml ~/.m2
            clojure -R:dev -e "(println \"Fetched deps\")"

      - save_cache:
          paths:
            - ~/.m2
            - ~/.gitlibs
          key: v1-dependencies-{{ checksum "deps.edn" }}

      - run:
          name: Run tests
          command: clojure -M:dev:test
