PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX pmdcat: <http://publishmydata.com/pmdcat#>

SELECT ?observation WHERE {
  ?dataset pmdcat:datasetContents ?cube .
  ?observation qb:dataSet ?cube .
}
#ORDER BY ?observation