PREFIX qb: <http://purl.org/linked-data/cube#>

SELECT DISTINCT ?dataset ?dimension ?value WHERE {
  {
    SELECT ?dataset (SAMPLE(?dimension) AS ?dimension) WHERE {
      ?dataset a qb:DataSet;
        qb:structure/qb:component/qb:dimension ?dimension .
    } GROUP BY ?dataset
  }

  ?observation qb:dataSet ?dataset;
    ?dimension ?value .
}
